services:
  php:
    build:
      args:
        user: socialgen_api_789_user
        uid: 1000
      context: .
      dockerfile: docker/php/Dockerfile
    container_name: socialgen_api_789-php
    working_dir: /var/www/html
    volumes:
      - .:/var/www/html
    networks:
      - socialgen_api_789_network

  nginx:
    image: nginx:alpine
    container_name: socialgen_api_789-nginx
    volumes:
      - .:/var/www/html
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8009:80" # To avoid conflict with another running container. Change to 8080:80 for example.
    depends_on:
      - php
    networks:
      - socialgen_api_789_network

  db:
    image: mysql:8
    container_name: socialgen_api_789-mysql
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: socialgen_api_789
      MYSQL_ROOT_PASSWORD: root
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    ports:
      - 3309:3306 # To avoid conflict with another running container. Change to 3307:3306 for example. Remember to use 3307 in your DBMS.
    volumes:
      - socialgen_api_789_dbdata:/var/lib/mysql
    networks:
      - socialgen_api_789_network

networks:
  socialgen_api_789_network:
    driver: bridge

volumes:
  socialgen_api_789_dbdata:
